# Generated by Django 5.1.3 on 2024-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_correct_label_feedback_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.TextField(unique=True)),
                ('correct_label', models.CharField(max_length=10)),
                ('pie_chart_base64', models.TextField()),
            ],
        ),
    ]
