# Generated by Django 5.1.3 on 2024-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_newsimprovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimprovement',
            name='token_saliency',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsimprovement',
            name='article_text',
            field=models.TextField(),
        ),
    ]
