# Generated by Django 5.1.3 on 2024-11-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_newsimprovement_token_saliency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimprovement',
            name='token_saliency',
        ),
    ]
